{"uuid": "2bb4e317-a333-45d3-8300-9193d1ffa33c", "children": ["0c106c72-e61f-42a7-b918-294bc722e6c3"], "befores": [{"name": "new_context", "status": "passed", "start": 1734868545578, "stop": 1734868545581}], "afters": [{"name": "new_context::0", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.TargetClosedError: BrowserContext.close: Target page, context or browser has been closed\nBrowser logs:\n\n<launching> C:\\Users\\Serjan777\\AppData\\Local\\ms-playwright\\chromium-1134\\chrome-win\\chrome.exe --disable-field-trial-config --disable-background-networking --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate,HttpsUpgrades,PaintHolding,PlzDedicatedWorker --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --disable-search-engine-choice-screen --unsafely-disable-devtools-self-xss-warnings --no-sandbox --user-data-dir=C:\\Users\\SERJAN~1\\AppData\\Local\\Temp\\playwright_chromiumdev_profile-TybEeI --remote-debugging-pipe --no-startup-window\n<launched> pid=7036\n[pid=7036][err] [7036:13704:1222/145845.560:ERROR:device_event_log_impl.cc(201)] [14:58:45.561] Bluetooth: bluetooth_adapter_winrt.cc:1055 Getting Default Adapter failed.\n[pid=7036][err] [7036:15600:1222/145848.267:ERROR:cpu_probe_win.cc(112)] PdhAddEnglishCounter failed: Error (0x13D) while retrieving error. (0xC0000BB8)\n[pid=7036][err] [7036:15600:1222/145848.267:ERROR:cpu_probe_win.cc(112)] PdhAddEnglishCounter failed: Error (0x13D) while retrieving error. (0xC0000BB8)\n[pid=7036][err] [7036:15600:1222/145945.419:ERROR:cpu_probe_win.cc(112)] PdhAddEnglishCounter failed: Error (0x13D) while retrieving error. (0xC0000BB8)\n[pid=7036] <gracefully close start>\n", "trace": "  File \"C:\\Users\\Serjan777\\miniconda3\\Lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Serjan777\\miniconda3\\Lib\\site-packages\\_pytest\\fixtures.py\", line 911, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\Serjan777\\miniconda3\\Lib\\site-packages\\pytest_playwright\\pytest_playwright.py\", line 338, in new_context\n    context.close()\n  File \"C:\\Users\\Serjan777\\miniconda3\\Lib\\site-packages\\pytest_playwright\\pytest_playwright.py\", line 329, in _close_wrapper\n    original_close(*args, **kwargs)\n  File \"C:\\Users\\Serjan777\\miniconda3\\Lib\\site-packages\\playwright\\sync_api\\_generated.py\", line 13170, in close\n    return mapping.from_maybe_impl(self._sync(self._impl_obj.close(reason=reason)))\n                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Serjan777\\miniconda3\\Lib\\site-packages\\playwright\\_impl\\_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\Serjan777\\miniconda3\\Lib\\site-packages\\playwright\\_impl\\_browser_context.py\", line 552, in close\n    await self._channel.send(\"close\", {\"reason\": reason})\n  File \"C:\\Users\\Serjan777\\miniconda3\\Lib\\site-packages\\playwright\\_impl\\_connection.py\", line 59, in send\n    return await self._connection.wrap_api_call(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Serjan777\\miniconda3\\Lib\\site-packages\\playwright\\_impl\\_connection.py\", line 514, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\n"}, "start": 1734868894070, "stop": 1734868894190}], "start": 1734868545578, "stop": 1734868894190}